name: flutterwolrd_br
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  youtube_player_flutter: ^6.1.0+4
  flutter_youtube: ^2.0.0
  video_player: ^0.10.8+1
  gen_profile: ^0.2.1
  google_sign_in: ^4.1.1
  firebase_auth: ^0.15.4
  google_fonts: ^0.3.9
  dio: ^3.0.8
  flutter_mobx: ^1.0.1
  mobx: ^1.0.1
  flutter_modular: ^0.4.2
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.0.1
  build_runner: ^1.7.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/g_logo.png

  # fonts:


scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs --use-polling-watcher